Angel update community
bookflix-devf/bookflix-api pull request #12
Opened 2024-07-09 03:11 UTC by arano1212

segun asi lo entendi espero este bien

2024-07-09 03:28 UTC, servo98 requested changes

2024-07-09 03:28 UTC, servo98 commented on api/api.js
> +api.use('/author', authorRouter)
/authors/:authorId/Community/:communityId

2024-07-09 03:28 UTC, servo98 commented on api/routes/authorRoutes.js
> +authorRouter.use('/:authorId/community', communityRouter)
`authorRouter.use('/:authorId/communities', communityRouter)`

2024-07-11 02:05 UTC, arano1212 commented on api/routes/authorRoutes.js
> +authorRouter.use('/:authorId/community', communityRouter)
dijeron que communities

2024-07-11 02:28 UTC, servo98 requested changes

2024-07-11 02:28 UTC, servo98 commented on api/validators/updateCommunitySchema.js
> +  authorId: Joi.string().pattern(/^[0-9a-fA-F]{24}$/).required(),
No debes cambiar de autor no puedes transferir tu comunidad a alguien más

2024-07-11 02:28 UTC, servo98 commented on api/controllers/communityControllers/communityController.js
> +      }
agregar validación de que solo puedes modificar tus propias comunidades

2024-07-11 03:14 UTC, arano1212 commented on api/validators/updateCommunitySchema.js
> +  authorId: Joi.string().pattern(/^[0-9a-fA-F]{24}$/).required(),
:)

2024-07-11 03:15 UTC, arano1212 commented on api/controllers/communityControllers/communityController.js
> +      }
agregue mas d euna validacion pero mi vscode craqueo  no puede avanzar mas con el  peor envio lo qu erealice espero este bien

2024-07-16 03:33 UTC, servo98 approved these changes

2024-07-16 03:33 UTC, merged